spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Gecadav_Data
    username: postgres
    password: simone
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data-main.sql
